aep/admin/routes.py
from flask import Blueprint, url_for, render_template, flash
from flask_login import current_user
from aep import db, current_worker
from flask import request , redirect, abort
from aep.admin.forms import SportingEventForm
from aep.models import Sporting_Event, Venue, Sport
from wtforms_alchemy import QuerySelectField

admin = Blueprint('admin',__name__)

@admin.route('/admin/', methods = ['GET', 'POST'])
def admin_default():
    
    form1 = SportingEventForm()
    
    venue_data = db.session.query(Venue.Venue_ID, Venue.Venue_Location).all()
    sport_data = db.session.query(Sport.Sport_ID, Sport.Sport_Name).all()
    form1.venue_list.choices = venue_data
    form1.sport_list.choices = sport_data

    if form1.is_submitted():
        
        sporting_event = Sporting_Event(
             SportingEvent_Name=form1.event_name.data,
             SportingEvent_Date=form1.event_date.data,
             SportingEvent_Time=form1.event_time.data,
             Venue_ID=form1.venue_list.data,
             Sport_ID=form1.sport_list.data)
        
        print('Made it to the submit the data!')

        db.session.add(sporting_event)
        db.session.commit()
        flash('Sporting Event has been added', 'success')
        return redirect(url_for('main.mainpage'))
     
    if current_user.is_authenticated:

        if current_user.role.Role_Name == 'Admin':
            return render_template ('admin.html', title = 'Admin Page', form1 = form1, venue_data = venue_data, sport_data = sport_data)
        else:
            flash('You do not have access to this page.', 'danger')
            return redirect(url_for('main.mainpage'))
    else:
        return redirect(url_for('users.login'))

 
@admin.route('/api/tables')
def api_tables():
    if current_user.is_authenticated:
        return "<h1 style='color: blue'>API Table Listing</h1>"
    else:
          return redirect(url_for('users.login'))

@admin.route('/api/sql')
def api_sql():
    if current_user.is_authenticated:
        return "<h1 style='color: green'>API SQL VIEWS</h1>"
    else:
          return redirect(url_for('users.login'))      

aep/main/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect
from flask_login import login_user, current_user, logout_user
from aep.models import Sporting_Event,Venue, Sport,Sport_Essential,SportingEvent_Detail,Worker,Transportation
from aep import db
from datetime import datetime

#from datetime import DateTime
#from flask import jsonify

main = Blueprint('main',__name__)

@main.route('/')
@main.route('/home')
def index():
# SECURITY CHECK AUTHENTICATION
     if current_user.is_authenticated:
          return render_template('mainpage.html', title='Main Page')
     else:
          return redirect(url_for('users.login'))

     
@main.route('/mainpage')
def mainpage():
     if current_user.is_authenticated:
          
          current_date = datetime.now()
          
          query_data = db.session.query(
                         Sporting_Event.SportingEvent_Name,
                         Sporting_Event.SportingEvent_Date,
                         Sporting_Event.SportingEvent_Time,
                         Venue.Venue_Location,
                         Venue.Venue_City,
                         Venue.Venue_State,
                         Venue.Venue_ZipCode,
                         Sport.Sport_Name,
                         Sport.Sport_Image,
                         SportingEvent_Detail.TransportationVan_Driver,
                         SportingEvent_Detail.SportEssential_Quantity,
                         Worker.Worker_FirstName,
                         Worker.Worker_LastName,
                         Transportation.Transportation_VanName,
                         Transportation.Transportation_PlateNumber,
                         Sport_Essential.SportEssential_Name,
                         Sport_Essential.SportEssential_Category)\
               .outerjoin(Venue, Sporting_Event.Venue_ID == Venue.Venue_ID) \
               .outerjoin(Sport, Sporting_Event.Sport_ID == Sport.Sport_ID) \
               .outerjoin(SportingEvent_Detail, Sporting_Event.SportingEvent_ID == SportingEvent_Detail.SportingEvent_ID) \
               .outerjoin(Worker, SportingEvent_Detail.Worker_ID == Worker.Worker_ID) \
               .outerjoin(Transportation, SportingEvent_Detail.Transportation_ID == Transportation.Transportation_ID) \
               .outerjoin(Sport_Essential, SportingEvent_Detail.SportEssential_ID == Sport_Essential.SportEssential_ID) \
               .filter(Sporting_Event.SportingEvent_Date >= current_date) \
               .order_by(Sporting_Event.SportingEvent_Date.asc())\
               .limit(3).all()
                    
          if current_user.role.Role_Name == 'Admin': 
               is_admin = True 
          else:
               is_admin = False
          
          print(f"Number of results: {len(query_data)}")
               
          print ('Here is Query')
          print (query_data)
          print ('End of Query')

          return render_template('mainpage.html', title='Main Page', query_data = query_data, is_admin = is_admin)

     else:
          return redirect(url_for('users.login'))

aep/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user
from aep import bcrypt
from aep import current_worker
from aep.models import Worker
from aep.users.forms import LoginForm
 
 
 
users = Blueprint('users', __name__)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))



@users.route('/login', methods=['GET', 'POST'])
def login():
    not_logged_in = False
    if current_user.is_authenticated:
        return redirect(url_for('main.mainpage'))
    else:
        not_logged_in = True

    form = LoginForm()
    
    if form.validate_on_submit():
        user = Worker.query.filter_by(Worker_Email=form.Worker_Email.data).first()
        if user and (user.Worker_Password == form.Worker_Password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('main.mainpage'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form, not_logged_in=not_logged_in)

aep/templates/admin.html
{% extends "layout.html" %}

{% block content %}
  <!--Body Code Start-->
      <!--Hero Image Code-->     
      <div class="hero-image">
        <div class="hero-text">
          <h1>Welcome!</h1>
          <h2>Communicate and be on the loop</h2>
        </div>
      </div>
    <div class="background-picture-body">
      <h3>Event Planning Administration</h3>
      <div class="admin_form">
        <form method="post" action="http://127.0.0.1:5000/admin">
            {{ form1.hidden_tag() }}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4">Add the Event</legend>
              <div class="form-group">
                {{ form1.event_name.label(class="form-control-label")}}
                {{ form1.event_name(class="form-control-label form-control-lg")}}
              </div>
              <div class="form-group">
                {{ form1.event_date.label(class="form-control-label")}}
                {{ form1.event_date(class="form-control-label form-control-lg")}}
              </div>
              <div class="form-group">
                {{ form1.event_time.label(class="form-control-label")}}
                {{ form1.event_time(class="form-control-label form-control-lg")}}
              </div>
              <div>
                <label for="Select Sport Dropdown">Select the Sport</label>
                <div class="dropdown">
                   <select class="form-control form-control-lg" data-header="Select the Sport" name="sport_list" style="width: 100%" id="sport_id">
                      {% for sport in sport_data %}
                        <option value="{{ sport[0] }}">{{sport[1]}}</option>
                      {% endfor %}
                   </select>
                </div>
              </div>
              <div>
                <label for="Select Venue Dropdown">Select the Venue</label>
                <div class="dropdown">
                   <select class="form-control form-control-lg" data-header="Select the Venue" name="venue_list" style="width: 100%" id = "venue_id">
                      {% for venue in venue_data %}
                        <option value="{{ venue[0] }}">{{venue[1]}}</option>
                      {% endfor %}
                   </select>
                </div>
             </div>
            </fieldset>
            <div class="form-group" style = "text-align:center">
              {{ form1.submit_event(class="btn btn-outline-info")}}
            </div>            
        </form>
      </div>
    </div>
  <!--Body Code End-->
{% endblock content %}

aep/templates/home.html
{% extends "layout.html" %}
{% block content %}

{% endblock content %}

aep/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='/css/style.css') }}">

      {% if title %}
          <title>Athletics Event Planner - {{ title }}</title>
      {% else %}
          <title>Athletics Event Planner</title>
      {% endif %}
  </head>
  <body>
    <header>
      <!--Top Menu-->
      <nav id="header-nav">
        
          <!--<a href="mainpage.html" id="header-logo"><img src="images/AU-ath-logo.png"></a>-->
          <a href="{{ url_for('main.mainpage') }}">AU Athletics Connect</a>
          {% if is_admin %}

          <a class="admin_icon" href="{{ url_for('admin.admin_default') }}" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                  </svg> Admin</a>
          {%endif%}
          {% if not_logged_in %}
          {% else %}
          <a class="logout" href="{{ url_for('users.logout') }}" ><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
          </svg> </a>
          {%endif%}
      </nav>
    </header>
      <div class="container">
          {% block content %}{% endblock %}
      </div>
    
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <footer>
      <h6>&copy;2023 Alliance University | All rights reserved | Designed by Capstone</h6>
    </footer>  
  </body>
</html>

aep/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="background-picture-body-login">
        <div class="login_image_div">
        <img src="static/images/AU-ath-logo.png" class="login_image"  class = "login_image" alt="...."> 
        </div>
        <div class="content-login-section">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend><b>Log In</b></legend>
                    <div class="form-group">
                        {{ form.Worker_Email.label(class="form-control-label") }}
                        {% if form.Worker_Email.errors %}
                            {{ form.Worker_Email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.Worker_Email.errors %}
                                <div class="alert alert-danger" role="alert">
                                    {{ error }}
                                  </div>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.Worker_Email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.Worker_Password.label(class="form-control-label") }}
                        {% if form.Worker_Password.errors %}
                            {{ form.Worker_Password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.Worker_Password.errors %}
                                <div class="alert alert-danger" role="alert">
                                    {{ error }}
                                  </div>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.Worker_Password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

aep/templates/mainpage.html
{% extends "layout.html" %}

{% block content %}
  <!--Body Code Start-->
      <!--Hero Image Code-->     
      <div class="hero-image">
        <div class="hero-text">
          <h1>Welcome!</h1>
          <h2>Communicate and be on the loop</h2>
        </div>
      </div>
      <div class="background-picture-body">
      <!--Events Card Group-->
        <h3>Next Games On Schedule:</h3>
            <div class="card-group scrollcards">
              {% for query in query_data %}
              <div class="card">
                <img src="static/images/{{ query[8] }}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">{{ query[7] }}</h5>
                  <p class="card-text">{{ query[0] }}</p>
                  <p>{{ query[1] }} {{ query[2] }} </p>
                  <a href="#popup{{ loop.index }}" class="btn btn-primary">View More</a>
                </div>
              </div>
              <div id="popup{{ loop.index }}" class="overlay content">
                <div class="popup">
                  <h3>{{ query[7] }}</h3>
                  <br>
                  <p><strong>Date:</strong></p>
                  <p>{{ query[1] }}  {{ query[2] }} </p>
                  <p><strong>Location:</strong></p>
                  <p>{{ query[3] }}</p>
                  <p>{{ query[4] }}, {{ query[5] }} {{ query[6] }}.</p>
                  <p><strong>Van Driver: </strong>{{ query[9] }}</p>
                  <p><strong>Van Name: </strong>{{ query[13] }} <strong>Plate: </strong>{{ query[14] }}</p>
                  <p><strong>Worker: </strong>{{ query[12] }} </p>
                  <p><strong>Essential: </strong>{{ query[15] }}</p>
                  <a class="close" href="#">&times;</a>
                </div>
              </div>
          {% endfor %}
          </div>
      </div>
<!--Body Code End-->
{% block news %}
{% endblock news %}
{% endblock content %}

aep/templates/secondpage.html
{% extends "layout.html" %}
{% block content %}
    <h1>YOU ARE NOT THE ADMIN PLEASE TRY AGAIN. </h1>
{% endblock content %}